# Generated by Django 5.0 on 2024-03-29 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiones',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
